name: FRETraj-demo
channels:
  - rna-fretools
  - conda-forge
  - defaults
dependencies:
  - fretraj==0.2.2
  - cmake
  - pip
  - matplotlib
  - jupytext
  - seaborn
  - pip:
    - git+https://github.com/fdsteffen/Labellib@src-neighbour-nodes
