title: "" 
author: Fabio D. Steffen
email: fabio.steffen@chem.uzh.ch
logo: images/fretraj_logo.png
copyright: 2020-2021


execute:
  execute: off
  #execute: cache
  #exclude_patterns:
    #- 'trajectories.md'
    #- 'jupyter-notebook.md'

launch_buttons:
  binderhub_url: "https://mybinder.org"
  #thebe: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: fretraj.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/RNA-FRETools/fretraj
  path_to_book: docs
  branch: master

html:
  favicon: images/fretraj_logo.png
  use_issues_button: true
  use_repository_button: true

sphinx:
  extra_extensions:
    - 'sphinx.ext.autodoc'
    - 'sphinx.ext.napoleon'
    - 'sphinx.ext.viewcode'
    - 'sphinx.ext.mathjax'
    - 'sphinx.ext.ifconfig'

  config:
    napoleon_use_rtype: False
    napoleon_use_param: False
    napoleon_include_private_with_doc: True
