name: Build and deploy

on:
  push:
    branches: 
      - main
      - master
    paths:
      - 'src/**'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Test package
        run: |
          pip install -e ".[dev]"
          pytest
      



  build-sdist:
    if: startsWith(github.ref, 'refs/tags')
    name: Build source distribution
    runs-on: ubuntu-latest
    needs:
      - test-deploy
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build source dist
        run: pipx run build --sdist

      - name: Upload source dist
        uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/

  build-wheel:
    if: startsWith(github.ref, 'refs/tags')
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    needs:
      - test-deploy
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.0
        env:
          CIBW_SKIP: pp*

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}
          path: wheelhouse/*.whl


  pypi-publish:
    if: startsWith(github.ref, 'refs/tags')
    name: Upload if release
    needs: [build-wheel, build-sdist]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/frettraj
    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: cibw-*
          merge-multiple: true

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

