name: FRETraj PyMOL docker image

on: [workflow_dispatch]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: fdsteffen
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: pymol/Dockerfile
          push: true
          tags: rna-fretools/fretraj-pymol:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}