name: FRETraj docs

on: 
  push:
    paths:
    - 'docs/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: build docs
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        source $HOME/.poetry/env
        export POETRY_VIRTUALENVS_CREATE=false
        pip install jupyter-book matplotlib seaborn
        poetry install
        jupyter-book build docs
    - name: deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@3.6.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs/_build/html
