name: Upload to PyPI and Anaconda

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Build and publish to PyPI
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
      run: |
        poetry build
        poetry publish
    
    - name: Add conda to system path
      if: always()
      run: |
        echo $CONDA/bin >> $GITHUB_PATH   
    - name: Install conda dependencies
      run: |
        conda install conda-build
        conda install anaconda-client     
    - name: Build conda package
      env:
        PACKAGE: fretraj
      run: |
        mkdir build
        conda skeleton pypi $PACKAGE --noarch-python

        sed -i "s|pyqt5|pyqt|g" fretraj/meta.yaml
        sed -i "s|your-github-id-here|fdsteffen|g" fretraj/meta.yaml
        doc_url=`sed -n -e 's/^.*documentation = //p' pyproject.toml`
        dev_url=`sed -n -e 's/^.*repository = //p' pyproject.toml`
        sed -ir "s|(doc_url: )|\1$doc_url|g" fretraj/meta.yaml
        sed -ir "s|(dev_url: )|\1$dev_url|g" fretraj/meta.yaml

        conda-build $PACKAGE --output-folder build/ --channel conda-forge
    - name: Upload to Anaconda
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: |
        anaconda upload build/noarch/*.tar.bz2
        conda-build purge-all
