name: Upload to PyPI and Anaconda

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Build and publish to PyPI
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
      run: |
        poetry build
        poetry publish
    
    - name: Add conda to system path
      run: |
        echo $CONDA/bin >> $GITHUB_PATH   
    - name: Install conda dependencies
      run: |
        conda install conda-build
        conda install anaconda-client     
    - name: Build conda package
      env:
        PACKAGE: fretraj
      run: |
        conda skeleton pypi $PACKAGE --noarch-python
        
        # package specific edits of meta.yaml
        sed '/gui --help/d' $PACKAGE/meta.yaml
        sed -i "s|pyqt5|pyqt|g" $PACKAGE/meta.yaml

        # general edits of meta.yaml
        sed -r -i "s|(host:)|\1\n\    - poetry|g" $PACKAGE/meta.yaml
        sed -i "s|your-github-id-here|fdsteffen|g" $PACKAGE/meta.yaml
        doc_url=`sed -n -e 's/^.*documentation = //p' pyproject.toml`
        dev_url=`sed -n -e 's/^.*repository = //p' pyproject.toml`
        sed -r -i "s|(doc_url: )|\1$doc_url|g" $PACKAGE/meta.yaml
        sed -r -i "s|(dev_url: )|\1$dev_url|g" $PACKAGE/meta.yaml
        sed -r -i "s|(license_file: )|\1LICENSE|g" $PACKAGE/meta.yaml
        sed -r '/dev_url:/a \  description: |\n' $PACKAGE/meta.yaml | sed '/description/q' > tmp
        sed 's/^/    /' README.md | sed -r 's|#### ([a-zA-Z0-9_ ]*)|<h4>\1</h4>|g' |
        sed -r 's|### ([a-zA-Z0-9_ ]*)|<h3>\1</h3>|g' | sed -r 's|## ([a-zA-Z0-9_ ]*)|<h2>\1</h2>|g' |
        sed -r 's|# ([a-zA-Z0-9_ ]*)|<h1>\1</h1>|g' >> tmp && mv tmp $PACKAGE/meta.yaml

        conda-build $PACKAGE --output-folder build/ --channel conda-forge
    - name: Upload to Anaconda
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN_ORG }}
      run: |
        anaconda upload -u rna-fretools build/noarch/*.tar.bz2
        conda-build purge-all
